channels:
    - conda-forge
dependencies:
    - matplotlib
    - gudhi
    - pandas
    - jupyterlab>=0.35
    - numpy
    - scikit-learn
    - tensorflow
    - pip:
      - jupyterlab_latex
      - ipywidgets
      - numpy
